Adding check_mk scripts
kbase/admin_tools pull request #4
Opened 2017-05-12 18:50 UTC by kkellerlbl

Also moving aweadmin script to its own dir, and creating placeholder for the docker-compose config files for AWE clients.

2017-05-12 21:28 UTC, kkellerlbl commented
I don't think there's any sensitive information in this PR but it'd be good for someone else to look and make sure.

2017-05-17 21:05 UTC, sychan requested changes
Do the MySQL creds need to be stripped out?

2017-05-17 21:05 UTC, sychan commented on check_mk/check_galera.sh
> +password=mydbms
Is this sensitive?

2017-05-17 21:08 UTC, kkellerlbl commented on check_mk/check_galera.sh
> +password=mydbms
YES, oops.  The mysql servers aren't accessible off network but it's still bad to have it in there.

2017-05-17 21:11 UTC, kkellerlbl commented on check_mk/check_galera.sh
> +password=mydbms
Those credentials also only work from certain hosts.  But if there's an easy to strip those creds from my git history before merging that'd be good.

2017-05-17 21:20 UTC, kkellerlbl commented on check_mk/check_galera.sh
> +password=mydbms
Please don't merge yet, I'm trying to sanitize my repo.

2017-05-17 21:25 UTC, kkellerlbl commented on check_mk/check_galera.sh
> +password=mydbms
I think my repo is okay.  Unfortunately the credentials still appear in the text of the PR.  I'm not super paranoid about it but if there's a way to get rid of it that'd be good too.

2017-05-18 18:53 UTC, kkellerlbl commented on check_mk/check_galera.sh
> +password=mydbms
Our mysql creds are now changed, so it's probably safe to merge this PR.

2017-05-18 20:39 UTC, merged